### ISSUE TITLE
App failure 

### ISSUE THREAD

**Issue by cohenaj194** [ff14-advanced-market-search/saddlebag-with-pockets#118]
```
Application Error
TypeError: Failed to fetch
    at Ge (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-B2JEZHGK.js:9:3774)
    at Object.action (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-B2JEZHGK.js:9:17961)
    at Ut (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-B2JEZHGK.js:9:14087)
    at Sr (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-B2JEZHGK.js:9:10569)
    at Object.L [as send] (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-B2JEZHGK.js:9:5782)
    at https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-B2JEZHGK.js:9:19423
    at sl (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-CFSYE5O3.js:8:24289)
    at Xn (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-CFSYE5O3.js:8:42364)
    at https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-CFSYE5O3.js:8:40660
    at Sl (https://task-table-column-reorder.saddlebag-with-pockets.pages.dev/build/_shared/chunk-CFSYE5O3.js:1:1717)
```
![Screenshot_20221108-185805_Chrome](https://user-images.githubusercontent.com/17516896/200702163-02ba4329-83e9-4545-8c34-a3c7e2f8bc05.jpg)

**Comment by Acen** [comment]
Not enough context - reopen with reproduction info if it appears again
